/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_root_hping2_Main */

#ifndef _Included_com_root_hping2_Hping2
#define _Included_com_root_hping2_Hping2
#ifdef __cplusplus
extern "C" {
#endif

    /*
 * Class:     com_root_hping2_Hping2_Companion
 * Method:    invokeHping2
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_root_hping2_Hping2_00024Companion_invokeHping2
        (JNIEnv *, jobject, jobjectArray);
#ifdef __cplusplus
}
#endif
#endif