/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_root_hping2_Main */

#ifndef _Included_com_root_hping2_Main
#define _Included_com_root_hping2_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_root_hping2_Main
 * Method:    callMainFromJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_root_hping2_Main_callMainFromJNI
        (JNIEnv *, jobject);

/*
 * Class:     com_root_hping2_Main
 * Method:    callMainFromJNI2
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_root_hping2_Main_callMainFromJNI2
        (JNIEnv *, jobject, jchar);

/*
 * Class:     com_root_hping2_Main
 * Method:    callMainFromJNI3
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_com_root_hping2_Main_callMainFromJNI3
        (JNIEnv *, jobject, jcharArray);

/*
 * Class:     com_root_hping2_Main
 * Method:    callMainFromJNI4
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_root_hping2_Main_callMainFromJNI4
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif